version: '3'
services:
 redis: 
  image: "redis:alpine"
  ports:
   - "6300:6300"
  expose:
   - 6300
  restart:
   always
 node-app:
   build: .
   ports:
    - "5000:5000"
   expose:
    - 5000 
networks: 
   test_vm:
      name: test_vm
      driver: bridge




volumes:
   - .:/usr/src/service
   - /usr/src/service/node_modules/bcrypt/

#  dev:
#   image: node:14
#   volumes:
#    - .:/usr/src/service
#    - /usr/src/service/node_modules/bcrypt/
#   working_dir: /usr/src/service
#   command: bash -c "npm install && npm run dev"
#   ports:
#    - 1234:1234
#    - 1235:1235
#   expose:
#    - 1234
#    - 1235
#    - 6060
#    - 80
